spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
          handshake-timeout: 10000
          close-notify-flush-timeout: 3000
          close-notify-read-timeout: 0
          key-store-password: abc123

server:
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:cert.p12
    key-store-password: abc123
    key-store-type: PKCS12

