server:
  port: 8443
  servlet:
    context-path: /v1
  ssl:
    protocol: TLS
    key-store: classpath:keystore
    key-store-password: abc123
    key-store-type: JKS

spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.49.66:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

