server:
  port: 6443
  servlet:
    context-path: /v1
  ssl:
    protocol: TLS
    key-store: classpath:cert.p12
    key-store-password: abc123
    key-store-type: PKCS12

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.49.66:8848
  sentinel:
    transport:
      port: 8719
      dashboard: localhost:8080