server:
  port: 6443
  servlet:
    context-path: /v1
  ssl:
    protocol: TLS
    key-store: classpath:cert.p12
    key-store-password: abc123
    key-store-type: PKCS12

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.49.66:8848
    stream:
      bindings:
        alarm_output:
          destination: alarm_topic
          binder: kafka
      kafka:
        binder:
          brokers: 172.16.49.41:9092
          zkNodes: 172.16.49.41:2181
          requiredAcks: 1
  sentinel:
    transport:
      port: 8719
      dashboard: localhost:8080